image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cd 02-sqlite
      tar -zxvf node_modules.tar.gz
      rm node_modules.tar.gz
      gcc -O3 -c -Wall -Wextra -Ideps/sqlite/build -o bench.o bench.c
      gcc -static -mtune=native -march=native -flto -pthread -m64 -s -o bench-c bench.o $JUST_HOME/modules/sqlite/deps/sqlite/build/.libs/libsqlite3.a
      rm bench.o
      make -C /home/gitpod/.just/just-$JUST_VERSION clean runtime && sudo make -C /home/gitpod/.just/just-$JUST_VERSION install
      just build --clean --cleanall --static bench-just.js
      cp /home/gitpod/.just/just-$JUST_VERSION/bench-just ./
      deno bundle bench-deno.js > bench-deno-bundle.js
      cd ../05-http
      mkdir deps
      curl -L -o deps/usocket.tar.gz https://github.com/uNetworking/uSockets/archive/v0.8.1.tar.gz
      tar -zxvf deps/usocket.tar.gz
      make -C deps/uSockets-0.8.1/
      gcc -O3 -c -Wall -Wextra -Ideps/uSockets-0.8.1/src -o bench-usocket.o bench-usocket.c
      gcc -static -mtune=native -march=native -flto -pthread -m64 -s -o bench-usocket bench-usocket.o deps/uSockets-0.8.1/uSockets.a
      rm bench-usocket.o
      just build --clean --static bench-just-dumb-loop.js
      cd ..